create table if not exists public.early_access_submissions (
  id bigint generated by default as identity primary key,
  first_name text not null check (char_length(first_name) between 1 and 100),
  work_email text not null check (char_length(work_email) between 3 and 320),
  business_name text not null check (char_length(business_name) between 1 and 200),
  industry text not null check (char_length(industry) between 1 and 100),
  employee_count text not null check (char_length(employee_count) between 1 and 50),
  hiring_timeline text not null check (char_length(hiring_timeline) between 1 and 50),
  hardest_to_hand_off text not null check (char_length(hardest_to_hand_off) between 1 and 2000),
  phone text check (phone is null or char_length(phone) <= 50),
  created_at timestamptz not null default now()
);

alter table public.early_access_submissions enable row level security;

revoke all on table public.early_access_submissions from anon, authenticated;
grant insert on table public.early_access_submissions to anon, authenticated;
grant usage, select on sequence public.early_access_submissions_id_seq to anon, authenticated;

create policy "Anyone can request early access"
on public.early_access_submissions
for insert
to anon, authenticated
with check (true);

comment on table public.early_access_submissions is
  'Early access requests submitted through the Handoff marketing website.';
